import Link from "next/link";
import { EXPLORER_URL, POAP_ADDRESS, ACTIVE_CHAIN } from "@/lib/contract";

export const metadata = { title: "Docs" };

export default function DocsHome() {
  return (
    <>
      <h1>Onchain POAPs — how it all works</h1>
      <p>
        <strong>Onchain POAPs</strong> are proof-of-attendance tokens whose
        artwork and metadata live <em>entirely</em> on Base. There is no IPFS,
        no image server, no database — the SVG itself is stored in contract
        storage (via SSTORE2) and the metadata JSON is generated by the
        contract on demand. If Base exists, your POAP exists. Forever.
      </p>
      <h2>The 60-second mental model</h2>
      <ul>
        <li>Every POAP is an <strong>event</strong> registered on one shared, permissionless ERC-1155 contract. Anyone can create one — no gatekeepers.</li>
        <li>Each event gets a numeric ID; the token ID equals the event ID.</li>
        <li>Each wallet can mint <strong>at most 1</strong> of any given POAP — enforced by the contract across every minting method.</li>
        <li>The creator chooses how it&rsquo;s distributed: <Link href="/docs/public-mint">public mint</Link>, <Link href="/docs/allowlists">allowlist</Link>, <Link href="/docs/signatures">signatures / QR codes</Link>, or a direct airdrop — in any combination.</li>
        <li>POAPs can be <Link href="/docs/soulbound">soulbound</Link> (non-transferable — the credible &ldquo;I was there&rdquo; setting) or freely transferable.</li>
        <li>Creators have a <Link href="/docs/creator-permissions">30-day window</Link> after registration to adjust distribution. After that, everything is frozen forever.</li>
      </ul>
      <h2>Quick starts</h2>
      <h3>I&rsquo;m an event organizer</h3>
      <ol>
        <li><Link href="/create">Create a POAP</Link> — upload SVG artwork, fill in event details, pick soulbound + distribution.</li>
        <li>Distribute: open the public mint for casual events, set an <Link href="/docs/allowlists">allowlist</Link> for a known guest list, or use <Link href="/docs/signatures">QR-code signature minting</Link> at the venue.</li>
        <li>Watch mints roll in on your POAP page, and manage everything from the <em>Manage distribution</em> dashboard.</li>
      </ol>
      <h3>I&rsquo;m an attendee / collector</h3>
      <ol>
        <li>Get a POAP link or QR from an organizer — or <Link href="/explore">browse open mints</Link>.</li>
        <li>Connect a wallet and mint. It&rsquo;s free; you pay only Base gas (usually well under a cent).</li>
        <li>See everything you&rsquo;ve collected in <Link href="/gallery">your collection</Link>, and <Link href="/docs/verify">verify it onchain</Link> anytime.</li>
      </ol>
      <h2>The contract</h2>
      <p>
        This app is a pure frontend over the open-source{" "}
        <a href="https://github.com/jvaleskadevs/onchain-poaps" target="_blank" rel="noreferrer">OnchainPOAPs contract</a>{" "}
        deployed at{" "}
        <a href={`${EXPLORER_URL}/address/${POAP_ADDRESS}#code`} target="_blank" rel="noreferrer">
          <code>{POAP_ADDRESS}</code>
        </a>{" "}
        on {ACTIVE_CHAIN.name}. Every action you take here is a direct contract
        call from your own wallet — the app never holds keys or funds. See the{" "}
        <Link href="/docs/contract">contract reference</Link> for the full API.
      </p>
    </>
  );
}
