import { NextResponse } from "next/server";

/**
 * Farcaster Mini App manifest.
 * https://miniapps.farcaster.xyz/docs/guides/publishing
 *
 * The accountAssociation proves domain ownership and must be generated by the
 * deployer for their own domain (see DEPLOYMENT.md), then supplied via env.
 */
export function GET() {
  const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const manifest: Record<string, unknown> = {
    miniapp: {
      version: "1",
      name: "Onchain POAPs",
      iconUrl: `${APP_URL}/icon.png`,
      homeUrl: APP_URL,
      imageUrl: `${APP_URL}/og.png`,
      buttonTitle: "🪙 Open Onchain POAPs",
      splashImageUrl: `${APP_URL}/splash.png`,
      splashBackgroundColor: "#f8f3e8",
      subtitle: "Attendance, stamped onchain",
      description:
        "Create, distribute and collect POAPs that live 100% onchain on Base. Public mints, allowlists, QR signature claims at live events, and a stamp-album gallery.",
      primaryCategory: "social",
      tags: ["poap", "events", "base", "nft", "onchain"],
      tagline: "Stamp your attendance onchain",
      ogTitle: "Onchain POAPs",
      ogDescription: "Proof of attendance, forever onchain — on Base.",
      ogImageUrl: `${APP_URL}/og.png`,
    },
  };

  const header = process.env.NEXT_PUBLIC_FC_HEADER;
  const payload = process.env.NEXT_PUBLIC_FC_PAYLOAD;
  const signature = process.env.NEXT_PUBLIC_FC_SIGNATURE;
  if (header && payload && signature) {
    manifest.accountAssociation = { header, payload, signature };
  }

  return NextResponse.json(manifest, {
    headers: { "Cache-Control": "public, max-age=300" },
  });
}
